export const surpriseMePrompts = [
  "Create an image that captures the feeling of a stormy ocean at sunset.",
  "Draw a picture that portrays the beauty of a blooming garden in spring.",
  "Design an image that showcases the power and grace of a wild horse running free.",
  "Imagine a surreal landscape with floating islands and whimsical creatures.",
  "Create an art piece that embodies the peacefulness of a forest at dawn.",
  "Draw a picture that shows the awe-inspiring grandeur of a mountain range.",
  "Design an image that captures the spirit of a bustling city at night.",
  "Imagine a futuristic cityscape with sleek buildings and flying cars.",
  "Create an art piece that reflects the magic and mystery of a starry night sky.",
  "Draw a picture that evokes the tranquility of a calm lake in the mountains.",
  "Design an image that portrays the energy and movement of a dance performance.",
  "Imagine a fantastical creature that has never been seen before.",
  "Create an art piece that expresses the vibrancy and diversity of a multicultural community.",
  "Draw a picture that captures the essence of a vintage seaside town.",
  "Design an image that showcases the majesty of a soaring eagle in flight.",
  "Imagine a dreamlike landscape with floating bubbles and colorful flowers.",
  "Create an art piece that embodies the serenity of a Zen garden.",
  "Draw a picture that reflects the playfulness of a group of dolphins swimming in the ocean.",
  "Design an image that captures the beauty of a sunflower field in the summertime.",
  "Imagine a mysterious castle nestled in a foggy forest.",
  "Create an art piece that portrays the joy of a child playing with a balloon.",
  "Draw a picture that shows the complexity of a bustling market in a foreign country.",
  "Design an image that showcases the elegance of a ballet performance.",
  "Imagine a magical forest with glowing mushrooms and fireflies.",
  "Create an art piece that captures the excitement of a rollercoaster ride.",
  "Draw a picture that reflects the peacefulness of a rural countryside landscape.",
  "Design an image that portrays the majesty of a lion in the savannah.",
  "Imagine a whimsical underwater world with talking sea creatures.",
  "Create an art piece that embodies the energy of a rock concert.",
  "Draw a picture that captures the essence of a quiet coffee shop on a rainy day.",
  "Design an image that showcases the beauty of a traditional Japanese garden.",
  "Imagine a futuristic space station orbiting a distant planet.",
  "Create an art piece that expresses the wonder of a child gazing at the stars.",
  "Draw a picture that evokes the feeling of standing on a windy cliff overlooking the ocean.",
  "Design an image that portrays the playfulness of a group of puppies playing in a park.",
  "Imagine a mythical creature with the head of a lion and the body of a fish.",
  "Create an art piece that embodies the power and majesty of a thunderstorm.",
  "Draw a picture that reflects the beauty of a desert landscape at sunset.",
  "Design an image that showcases the elegance of a swan gliding across a lake.",
  "Imagine a cozy cabin in the woods with a crackling fireplace.",
  "Create an art piece that portrays the beauty of a snowy winter landscape.",
  "Draw a picture that captures the essence of a bustling street market in an exotic city.",
  "Design an image that evokes the feeling of floating in outer space.",
  "Imagine a mystical forest with towering trees and hidden creatures."
  ];